### ISSUE TITLE
Error while installing on windows 8

### ISSUE THREAD

**Issue by rmilesson** [6to5/gulp-6to5#10]
Getting the following while trying to install locally in a project on a machine running Windows 8. Am I missing a dependency or something?
```
PS C:\Development\ProjectName\ProjectName> npm install --save-dev gulp-6to5
npm WARN package.json ProjectName@1.0.0 No description
npm WARN package.json ProjectName@1.0.0 No repository field.
npm WARN package.json ProjectName@1.0.0 No README data
/


> kexec@0.2.0 install C:\Development\ProjectName\ProjectName\node_modules\gulp-6to5\node_modules\6to5\node_modul
es\kexec
> node-gyp configure build


C:\Development\ProjectName\ProjectName\node_modules\gulp-6to5\node_modules\6to5\node_modules\kexec>node "C:\Prog
ram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  kexec.cc
..\src\kexec.cc(9): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\Development\
ProjectName\ProjectName\node_modules\gulp-6to5\node_modules\6to5\node_modules\kexec\build\kexec.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
67:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "config
ure" "build"
gyp ERR! cwd C:\Development\ProjectName\ProjectName\node_modules\gulp-6to5\node_modules\6to5\node_modules\kexec
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.1
npm WARN optional dep failed, continuing kexec@0.2.0
gulp-6to5@2.0.0 node_modules\gulp-6to5
├── object-assign@2.0.0
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── 6to5@2.12.2 (fs-readdir-recursive@0.1.0, roadrunner@1.0.4, private@0.1.6, commander@2.5.0, estraverse@1.8.0, esutils
@1.1.6, esvalid@1.1.0, ast-types@0.6.7, mkdirp@0.5.0, source-map@0.1.40, chokidar@0.11.1, source-map-support@0.2.8, loda
sh@2.4.1, regexpu@0.3.0, regenerator@0.8.3, core-js@0.4.4, acorn-6to5@0.11.1-14, jshint@2.5.10)
PS C:\Development\ProjectName\ProjectName>
```

**Comment by sindresorhus** [comment]
> npm WARN **optional dep** failed, continuing

**Comment by rmilesson** [comment]
Ah, completely missed that. Thanks!
